[package]
name = "bevy_canvas_size"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.16.1", features = ["webgpu"] }
wasm-bindgen = "0.2.100"
